import { describe,it,expect } from "vitest";
import { audioExpired,cleanAudio,deleteInOrder,deletionSchema,exportSelections,pageSchema,retentionHours } from "./lifecycle";
import { translate,missingTranslations,messages } from "../../lib/i18n/core";
import { checkedResponse,friendlyError } from "../../lib/recovery";
const row={id:"a",user_id:"u",audio_object_path:"u/a.mp3",audio_deleted_at:null,audio_expires_at:null,created_at:"2026-01-01T00:00:00Z",processing_status:"completed"};
describe("lifecycle boundaries",()=>{
  it("retains successful audio up to 24h and failures up to 72h",()=>{expect(audioExpired(row,Date.parse("2026-01-02"))).toBe(true);expect(audioExpired({...row,processing_status:"failed"},Date.parse("2026-01-02"))).toBe(false);expect(audioExpired({...row,processing_status:"failed"},Date.parse("2026-01-04"))).toBe(true);});
  it("never cleans already deleted or invalid expiry",()=>{expect(audioExpired({...row,audio_deleted_at:"today"},Infinity)).toBe(false);expect(audioExpired({...row,audio_expires_at:"invalid"},Infinity)).toBe(false);expect(retentionHours("-1",24)).toBe(24);expect(retentionHours("12",24)).toBe(12);});
  it("marks audio only after removal, and retries after storage failure",async()=>{let marked=0,attempts=0;const remove=async()=>{if(!attempts++)throw new Error("network");};const mark=async()=>{marked++;};await expect(cleanAudio(row,remove,mark)).rejects.toThrow();expect(marked).toBe(0);await cleanAudio(row,remove,mark);expect(marked).toBe(1);expect(await cleanAudio({...row,audio_deleted_at:"today"},remove,mark)).toBe(false);});
  it("rejects cross-user object references",async()=>{await expect(cleanAudio({...row,audio_object_path:"other/file"},async()=>{},async()=>{})).rejects.toThrow("ownership");});
  it("retries a missing object after DB failure without losing evidence",async()=>{let marks=0;await expect(cleanAudio(row,async()=>{},async()=>{marks++;throw new Error();})).rejects.toThrow();await cleanAudio(row,async()=>{},async()=>{marks++;});expect(marks).toBe(2);});
  it("deletion queues first and does not delete Auth after failed storage removal",async()=>{const calls:string[]=[];await expect(deleteInOrder({queue:async()=>{calls.push("queue");},storage:async()=>{throw new Error();},identity:async()=>{calls.push("identity");},complete:async()=>{calls.push("done");}})).rejects.toThrow();expect(calls).toEqual(["queue"]);});
  it("supports retry-safe deletion orchestration",async()=>{const steps:string[]=[];const ops={queue:async()=>{steps.push("queue");},storage:async()=>{steps.push("storage");},identity:async()=>{steps.push("identity");},complete:async()=>{steps.push("done");}};await deleteInOrder(ops);await deleteInOrder(ops);expect(steps).toEqual(["queue","storage","identity","done","queue","storage","identity","done"]);});
  it("requires exact confirmation and rejects arbitrary identity",()=>{expect(deletionSchema.safeParse({confirmation:"DELETE"}).success).toBe(true);expect(deletionSchema.safeParse({confirmation:"DELETE",userId:"other"}).success).toBe(false);expect(deletionSchema.safeParse({confirmation:"yes"}).success).toBe(false);});
  it("export allowlist excludes operational and provider metadata",()=>{const fields=Object.values(exportSelections).join(",");expect(fields).not.toMatch(/metadata|provider|model|token|password|secret|user_id/);expect(exportSelections).not.toHaveProperty("evidence_events");});
  it("bounds pagination",()=>{expect(pageSchema.parse("2")).toBe(2);expect(pageSchema.parse("-4")).toBe(1);expect(pageSchema.parse("999999")).toBe(1);});
});
describe("localization and recovery",()=>{
  it("covers every catalog entry in all three languages",()=>expect(missingTranslations()).toEqual([]));
  it("falls back safely and detects missing translations",()=>{const source={greeting:{en:"Hello"}};expect(translate("zh","greeting",{},source)).toBe("Hello");expect(translate("es","unknown",{},source)).toBe("unknown");expect(missingTranslations(source)).toEqual(["zh:greeting","es:greeting"]);});
  it("covers major surfaces and dynamic progress",()=>{for(const key of ["Sign in","Home","My English","History","Settings","Membership","Export my data","Delete account","Voice preferences","Reset your password","Start assessment","Check response"]){expect(translate("zh",key)).not.toBe(key);expect(translate("es",key)).not.toBe(key);}expect(translate("zh","We're still learning about your listening.")).toContain("听力");expect(Object.keys(messages).length).toBeGreaterThan(300);});
  it("maps network and server errors without rendering raw diagnostics",async()=>{expect(friendlyError(new TypeError("fetch failed"))).toContain("offline");await expect(checkedResponse(new Response("secret stack",{status:503}))).rejects.toThrow("temporarily unavailable");await expect(checkedResponse(new Response("",{status:401}))).rejects.toThrow("session has expired");});
});
