import { describe, expect, it } from "vitest";
import { entryRoute, progressCards, recognitionGaps, progressTimeline, practiceNeeds, sessionSummary } from "./selectors";
import { editablePreferences, settingsSchema } from "./settings";
import { adEligible, deliveryCapabilities, membershipSummary, subscriptionActive } from "./commercial";
import { decide, correctionText, makeTask } from "../learning/engine";
import type { Snapshot } from "../learning/types";
const snapshot:Snapshot={revision:0,sessionId:"session",language:"en",abilities:[],knowledge:[],patterns:[],effects:[],preferences:[],goals:["daily_communication","work"],evidence:[],history:[],state:"normal",catalog:[]};
const settings={nativeLanguage:"en",interfaceLanguage:"zh",goals:[{key:"work",priority:5}],...editablePreferences([])};
describe("learner product summaries",()=>{
  it("routes each onboarding state without a loop",()=>{expect(entryRoute(false,false)).toBe("/onboarding");expect(entryRoute(true,false)).toBe("/assessment");expect(entryRoute(true,true)).toBe("/home");});
  it("keeps seven dimensions and honest empty states",()=>{const cards=progressCards([]);expect(cards).toHaveLength(7);expect(cards.every(c=>c.stage==="Needs more evidence")).toBe(true);expect(cards.some(c=>c.label==="English Score")).toBe(false);});
  it("low-confidence estimates remain tentative regardless of level",()=>{const card=progressCards([{dimension:"listening",estimate_level:5,confidence_level:1}])[0];expect(card.uncertain).toBe(true);expect(card.note).toContain("still learning");expect(card).not.toHaveProperty("confidence_level");});
  it("does not list unknown skills as weaknesses",()=>expect(practiceNeeds([{dimension:"listening",estimate_level:0,confidence_level:0}],[])).toEqual([]));
  it("shows recognition-production gaps only with reliable recognition",()=>{const k={knowledge_item_id:"one",modality:"reading_recognition" as const,state:"recognized",confidence_level:2,review_need:1,last_evidence_at:null};expect(recognitionGaps([k],new Map([["one","Make a request"]]))[0]).toContain("while speaking");expect(recognitionGaps([{...k,confidence_level:0}],new Map())).toEqual([]);expect(recognitionGaps([k,{...k,modality:"spoken_production",state:"independent"}],new Map())).toEqual([]);});
  it("uses real, sufficiently confident changes for improvement",()=>{const c={id:"one",changed_at:"2026-09-25",changed_entity_type:"ability",dimension:"listening",previous_value:{estimate_level:0},new_value:{estimate_level:1,confidence_level:1}};expect(progressTimeline([c])).toEqual([]);expect(progressTimeline([{...c,new_value:{estimate_level:1,confidence_level:2}}])[0].text).toContain("Listening");});
  it("neutral confidence-only changes do not fabricate progress",()=>expect(progressTimeline([{id:"a",changed_at:"today",changed_entity_type:"ability",dimension:"reading",previous_value:{estimate_level:1},new_value:{estimate_level:1,confidence_level:3}}])).toEqual([]));
  it("a first estimate is not mislabeled as improvement",()=>expect(progressTimeline([{id:"a",changed_at:"today",changed_entity_type:"ability",dimension:"reading",previous_value:null,new_value:{estimate_level:4,confidence_level:2}}])).toEqual([]));
  it("strong recognition is not described as independent production",()=>{const c={id:"a",changed_at:"today",changed_entity_type:"knowledge",dimension:null,previous_value:{state:"recognized"},new_value:{state:"strong",confidence_level:3,modality:"reading_recognition"}};expect(progressTimeline([c])).toEqual([]);expect(progressTimeline([{...c,new_value:{...c.new_value,modality:"spoken_production"}}])[0].text).toContain("while speaking");expect(progressTimeline([{...c,new_value:{...c.new_value,modality:"written_production"}}])[0].text).toContain("in writing");});
  it("empty history provides an accurate empty summary",()=>expect(sessionSummary("a","today",null,[])).toMatchObject({count:0,expressions:[],focus:[]}));
  it("home recommendation is selected by the same teaching engine",()=>expect(decide(snapshot).objective).toBe("Make a polite request"));
});
describe("editable self-reported preferences",()=>{
  it("validates and preserves priority without accepting ability inputs",()=>{expect(settingsSchema.parse(settings).goals[0].priority).toBe(5);expect(settingsSchema.safeParse({...settings,abilities:[]}).success).toBe(false);expect(settingsSchema.safeParse({...settings,entitlements:{ads_enabled:false}}).success).toBe(false);});
  it("requires distinct supported goals and nonempty selection",()=>{expect(settingsSchema.safeParse({...settings,goals:[]}).success).toBe(false);expect(settingsSchema.safeParse({...settings,goals:[{key:"work",priority:5},{key:"work",priority:2}]}).success).toBe(false);});
  it("preserves rejection and expands older onboarding aliases",()=>{const value=editablePreferences([{preference_type:"method",target_key:"speaking",strength:-2,value_text:null},{preference_type:"method",target_key:"writing",strength:1,value_text:null}]);expect(value.methods.speaking).toBe(-2);expect(value.methods.guided_writing).toBe(1);expect(settingsSchema.parse({...settings,methods:{...value.methods,speaking:2}}).methods.speaking).toBe(2);});
  it("maps all correction and pace options",()=>{for(const correction of ["immediate","gentle","after_turn","minimal"])for(const pace of ["gentle","balanced","brisk"])expect(settingsSchema.safeParse({...settings,correction,pace}).success).toBe(true);});
  it("goal priority changes teaching focus, not ability",()=>{const copy=structuredClone(snapshot);expect(decide({...copy,goals:["work","daily_communication"]}).topic).toBe("meeting_times");expect(copy).toEqual(snapshot);});
  it("challenge preference cannot override explicit overload",()=>{const overloaded={...snapshot,state:"overloaded",preferences:[{preference_type:"pace",target_key:"initial",value_text:"brisk",strength:1}],abilities:[{dimension:"vocabulary" as const,estimate_level:3,confidence_level:3}]};expect(decide(overloaded).difficulty).toBeLessThan(3);});
  it("minimal correction changes delivery, not measured ability",()=>{const s={...snapshot,preferences:[{preference_type:"correction",target_key:"initial",value_text:"minimal",strength:1}]};expect(decide(s).correction).toBe("move_on");expect(s.abilities).toEqual([]);});
  it("minimal correction lets meaning through but still helps failed communication",()=>{const d=decide({...snapshot,preferences:[{preference_type:"correction",target_key:"initial",value_text:"minimal",strength:1}]});const task=makeTask(d,0);expect(correctionText(d,task,2,[],0)).toContain("Keep the conversation going");expect(correctionText(d,task,0,["meaning"],0)).toContain("A useful model");});
});
describe("commercial surfaces are separate from learner need",()=>{
  it("ad slots need entitlement plus permitted placement",()=>{expect(adEligible({ads_enabled:true},{enabled:true,protected_surface:false},"dashboard",false)).toBe(true);expect(adEligible({ads_enabled:false},{enabled:true,protected_surface:false},"dashboard",false)).toBe(false);expect(adEligible({ads_enabled:true},null,"dashboard",false)).toBe(false);});
  it("never allows protected or unknown surfaces",()=>{for(const surface of ["assessment","recording","answering","correction","targeted_practice","learn"]){expect(adEligible({ads_enabled:true},{enabled:true,protected_surface:false},surface,false)).toBe(false);}expect(adEligible({ads_enabled:true},{enabled:true,protected_surface:false},"dashboard",true)).toBe(false);expect(adEligible({ads_enabled:true},{enabled:true,protected_surface:true},"progress",false)).toBe(false);});
  it("uses effective entitlements, not plan labels",()=>{expect(deliveryCapabilities({can_use_voice:true,ads_enabled:false})).toMatchObject({voice:true,ads:false});expect(membershipSummary("Whatever",{ads_enabled:false}).ads).toBe("Ad placements disabled");});
  it("membership preview contains no checkout or price",()=>{const m=membershipSummary("Free",{});expect(m.paymentNotice).toContain("not enabled");expect(m).not.toHaveProperty("price");expect(m.future.every(f=>!f.eligible)).toBe(true);});
  it("expired/canceled/future subscriptions cannot grant capabilities",()=>{const now=new Date("2026-09-25");const sub={status:"active",started_at:"2026-09-01",ends_at:null};expect(subscriptionActive(sub,now)).toBe(true);for(const status of ["expired","canceled","payment_issue"])expect(subscriptionActive({...sub,status},now)).toBe(false);expect(subscriptionActive({...sub,ends_at:"2026-09-20"},now)).toBe(false);expect(subscriptionActive({...sub,started_at:"2026-10-01"},now)).toBe(false);expect(subscriptionActive({...sub,status:"trial"},now)).toBe(true);});
});
