import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { expect,test,type Page } from "@playwright/test";
import { maintainVoice } from "../scripts/voice-maintenance";
import type { Database } from "../src/types/database.generated";
const admin=()=>createClient<Database>(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});
async function learner(page:Page){const db=admin();const email=`lifecycle-${randomUUID()}@example.test`,password=randomUUID();const r=await db.auth.admin.createUser({email,password,email_confirm:true});expect(r.error).toBeNull();const user=r.data.user!;
  expect((await db.from("profiles").update({onboarding_status:"completed",interface_language:"en",native_language:"zh"}).eq("user_id",user.id)).error).toBeNull();await db.from("learning_sessions").insert({user_id:user.id,status:"completed",starting_state_summary:{purpose:"initial_assessment_v1"},session_summary:{complete:true,turns:[]},ending_state_summary:{model:[],support:"native_supported"}});
  await page.goto("/login");const form=page.getByRole("heading",{name:"Sign in",exact:true}).locator("..");await form.getByLabel("Email",{exact:true}).fill(email);await form.getByLabel("Password",{exact:true}).fill(password);await form.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page).toHaveURL(/\/home$/);return {db,user,email,password,cleanup:()=>db.auth.admin.deleteUser(user.id)};
}
const origin={origin:"http://127.0.0.1:3000"};
test("lifecycle A: real recovery token sets a new password and invalid tokens recover safely",async({page})=>{
  const f=await learner(page);try{await page.goto("/settings");await page.getByRole("button",{name:"Sign out",exact:true}).click();await page.getByRole("link",{name:"Forgot password?"}).click();await expect(page).toHaveURL(/\/auth\/recovery$/);await page.getByLabel("Email",{exact:true}).fill(f.email);await page.getByRole("button",{name:"Send recovery link"}).click();await expect(page.getByRole("status")).toContainText("If an account exists");
    const link=await f.db.auth.admin.generateLink({type:"recovery",email:f.email});expect(link.error).toBeNull();await page.goto(`/auth/confirm?type=recovery&token_hash=${link.data.properties!.hashed_token}`);await expect(page).toHaveURL(/\/auth\/reset$/);const password=randomUUID();await page.getByLabel("New password",{exact:true}).fill(password);await page.getByRole("button",{name:"Save new password"}).click();await expect(page).toHaveURL(/\/login\?message=password_updated/);
    const fresh=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{auth:{persistSession:false}});expect((await fresh.auth.signInWithPassword({email:f.email,password})).error).toBeNull();await fresh.auth.signOut();await page.goto("/auth/confirm?type=recovery&token_hash=invalid");await expect(page.locator("main [role=alert]")).toContainText("expired or is invalid");await page.goto("/auth/reset");await expect(page).toHaveURL(/recovery\?error=expired/);
  }finally{await f.cleanup();}
});
test("lifecycle B: export contains only owned readable data and rejects arbitrary identity",async({page})=>{
  const f=await learner(page);const other=await f.db.auth.admin.createUser({email:`other-${randomUUID()}@example.test`,password:randomUUID(),email_confirm:true});try{await f.db.from("user_feedback").insert([{user_id:f.user.id,feedback_type:"learner_note",free_text:"MY_PRIVATE_NOTE"},{user_id:other.data.user!.id,feedback_type:"learner_note",free_text:"OTHER_PRIVATE_NOTE"}]);await page.goto("/settings");const downloadPromise=page.waitForEvent("download");await page.getByRole("button",{name:"Export my data"}).click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe("adaptive-english-data.json");const stream=await download.createReadStream();let text="";for await(const part of stream!)text+=part.toString();const data=JSON.parse(text);expect(data.email).toBe(f.email);expect(text).toContain("MY_PRIVATE_NOTE");expect(text).not.toContain("OTHER_PRIVATE_NOTE");expect(text).not.toContain("service_role");expect(data).not.toHaveProperty("evidence_events");const forged=await page.request.post("/api/account",{headers:origin,data:{action:"export",userId:other.data.user!.id}});expect(forged.status()).toBe(400);const csrf=await page.request.post("/api/account",{headers:{origin:"https://elsewhere.test"},data:{action:"export"}});expect(csrf.status()).toBe(403);
  }finally{await f.cleanup();await f.db.auth.admin.deleteUser(other.data.user!.id);}
});
test("lifecycle C: explicit deletion removes real storage and cascades owned data",async({page})=>{
  const f=await learner(page);const path=`${f.user.id}/test/delete.mp3`;try{expect((await f.db.storage.from("voice-temp").upload(path,new Uint8Array(128),{contentType:"audio/mpeg"})).error).toBeNull();await f.db.from("learning_goals").insert({user_id:f.user.id,goal_type:"work"});await page.goto("/settings");await page.getByRole("button",{name:"Delete account",exact:true}).click();const dialog=page.getByRole("dialog");await expect(dialog).toBeVisible();await expect(dialog.getByRole("button",{name:"Permanently delete",exact:true})).toBeDisabled();await dialog.getByLabel("Type DELETE to confirm").fill("DELETE");await dialog.getByRole("button",{name:"Permanently delete",exact:true}).click();await expect(page).toHaveURL(/\/login\?message=deleted/);expect((await f.db.auth.admin.getUserById(f.user.id)).data.user).toBeNull();for(const table of ["profiles","learning_goals","learning_sessions","voice_interactions","user_feedback","user_entitlement_overrides","usage_records"] as const)expect((await f.db.from(table).select("user_id").eq("user_id",f.user.id)).data).toEqual([]);expect((await f.db.storage.from("voice-temp").download(path)).error).not.toBeNull();expect((await f.db.from("plans").select("id")).data!.length).toBeGreaterThan(0);expect((await page.request.post("/api/account",{headers:origin,data:{confirmation:"DELETE"}})).status()).toBe(401);
  }finally{await f.db.storage.from("voice-temp").remove([path]);await f.cleanup();}
});
test("lifecycle D: English Chinese Spanish switch without changing support language or ability",async({page})=>{
  const f=await learner(page);try{await f.db.from("learner_ability_estimates").insert({user_id:f.user.id,dimension:"reading",estimate_level:3,confidence_level:2});for(const [locale,title,nav] of [["zh","设置","主导航"],["es","Ajustes","Navegación principal"],["en","Settings","Main navigation"]]){await page.goto("/settings");await page.locator('.language-picker select').selectOption(locale);await expect(page.locator("html")).toHaveAttribute("lang",locale);await expect(page.getByRole("heading",{name:title,exact:true})).toBeVisible();await expect(page.getByRole("navigation",{name:nav})).toBeVisible();}expect((await f.db.from("profiles").select("native_language").eq("user_id",f.user.id).single()).data!.native_language).toBe("zh");expect((await f.db.from("learner_ability_estimates").select("estimate_level").eq("user_id",f.user.id)).data).toEqual([{estimate_level:3}]);}finally{await f.cleanup();}
});
test("lifecycle E: temporary disconnect and expired auth preserve activity draft",async({page,context})=>{
  const f=await learner(page);try{await f.db.from("learning_preferences").insert({user_id:f.user.id,preference_type:"method",target_key:"conversation",strength:2,confidence_level:3,source:"explicit_feedback"});await page.goto("/learn");await page.getByRole("button",{name:"Start learning session",exact:true}).click();await page.getByRole("textbox",{name:"Your response",exact:true}).fill("Water please");await context.setOffline(true);await expect(page.getByText(/Your input stays here/)).toBeVisible();await page.getByRole("button",{name:"Check response",exact:true}).click();await expect(page.locator(".error[role=alert]")).toContainText("offline");await expect(page.getByRole("textbox",{name:"Your response",exact:true})).toHaveValue("Water please");await context.setOffline(false);
    await page.route("**/api/learning",route=>route.fulfill({status:401,contentType:"application/json",body:'{"error":"expired"}'}));await page.getByRole("button",{name:"Check response",exact:true}).click();await expect(page.locator(".error[role=alert]")).toContainText("session has expired");await expect(page.getByRole("textbox",{name:"Your response",exact:true})).toHaveValue("Water please");await page.unroute("**/api/learning");await page.reload();await expect(page.getByRole("textbox",{name:"Your response",exact:true})).toHaveValue("Water please");await page.getByRole("button",{name:"Read instead",exact:true}).click();await page.getByRole("button",{name:"Check response",exact:true}).click();await expect(page.getByRole("textbox",{name:"Your response",exact:true})).toHaveValue("");const e=await f.db.from("evidence_events").select("id").eq("user_id",f.user.id).eq("evidence_kind","learning_performance");expect(e.data).toHaveLength(1);
  }finally{await context.setOffline(false);await f.cleanup();}
});
test("lifecycle F: cleanup removes expired audio, preserves transcript, and is idempotent",async({page})=>{
  const f=await learner(page);const path=`${f.user.id}/test/expired.mp3`;try{await page.goto("/learn");await page.getByRole("button",{name:"Start learning session",exact:true}).click();const view=await(await page.request.get("/api/learning")).json();expect((await f.db.storage.from("voice-temp").upload(path,new Uint8Array(128),{contentType:"audio/mpeg"})).error).toBeNull();const row=await f.db.from("voice_interactions").insert({user_id:f.user.id,session_id:view.sessionId,activity_id:view.activityId,interaction_type:"tts",audio_object_path:path,audio_expires_at:"2020-01-01",processing_status:"completed",transcript:"keep this learning transcript"}).select("id").single();expect(row.error).toBeNull();expect((await maintainVoice(f.db)).failed).toBe(0);const saved=await f.db.from("voice_interactions").select("transcript,audio_object_path,audio_deleted_at").eq("id",row.data!.id).single();expect(saved.data?.transcript).toBe("keep this learning transcript");expect(saved.data?.audio_object_path).toBeNull();expect(saved.data?.audio_deleted_at).toBeTruthy();expect((await f.db.storage.from("voice-temp").download(path)).error).not.toBeNull();expect((await maintainVoice(f.db)).failed).toBe(0);}finally{await f.db.storage.from("voice-temp").remove([path]);await f.cleanup();}
});
test("lifecycle G: mobile account dialog and main learning flow remain accessible",async({page})=>{
  const f=await learner(page);try{for(const width of [390,768,1280]){await page.setViewportSize({width,height:844});for(const path of ["/assessment","/learn","/settings","/membership"]){await page.goto(path);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.goto("/settings");await page.getByRole("button",{name:"Delete account",exact:true}).click();await expect(page.getByRole("dialog")).toBeInViewport();await page.keyboard.press("Escape");await expect(page.getByRole("dialog")).not.toBeVisible();await expect(page.getByRole("button",{name:"Delete account",exact:true})).toBeFocused();}}finally{await f.cleanup();}
});
