import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { expect, test, type Page } from "@playwright/test";
import { speechMock } from "./speech-mock";
async function fixture(page:Page,assessed=true){
  const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!);const email=`product-${randomUUID()}@example.test`;const password=randomUUID();const result=await db.auth.admin.createUser({email,password,email_confirm:true});if(result.error||!result.data.user)throw Error("Fixture failed");const user=result.data.user;
  if(assessed){const setup=await Promise.all([db.from("profiles").update({onboarding_status:"completed",native_language:"en",interface_language:"en"}).eq("user_id",user.id),db.from("learning_sessions").insert({user_id:user.id,status:"completed",starting_state_summary:{purpose:"initial_assessment_v1"},session_summary:{complete:true,turns:[]}})]);setup.forEach(r=>expect(r.error).toBeNull());}
  await page.goto("/login");const form=page.getByRole("heading",{name:"Sign in",exact:true}).locator("..");await form.getByPlaceholder("Email").fill(email);await form.getByPlaceholder("Password").fill(password);await form.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page).toHaveURL(assessed?/\/home$/:/\/assessment$/);
  return {db,user,email,cleanup:()=>db.auth.admin.deleteUser(user.id)};
}
test("product A: Home derives focus and resumes one learning session",async({page})=>{
  const f=await fixture(page);try{await expect(page.getByRole("heading",{name:"Current focus",exact:true})).toBeVisible();await expect(page.getByText("Make a polite request",{exact:true})).toBeVisible();await page.getByRole("link",{name:"Start learning",exact:true}).click();await page.getByRole("button",{name:"Start learning session",exact:true}).click();await expect(page.getByRole("button",{name:"Check response",exact:true})).toBeVisible();await page.getByRole("link",{name:"Home",exact:true}).click();await page.getByRole("link",{name:"Continue session",exact:false}).click();await expect(page.getByRole("button",{name:"Check response",exact:true})).toBeVisible();const sessions=await f.db.from("learning_sessions").select("id").eq("user_id",f.user.id).contains("starting_state_summary",{purpose:"normal_learning_v1"});expect(sessions.data).toHaveLength(1);}finally{await f.cleanup();}
});
test("product B: separate progress dimensions, uncertainty and real history",async({page})=>{
  const f=await fixture(page);try{
    expect((await f.db.from("learner_ability_estimates").insert([{user_id:f.user.id,dimension:"listening",estimate_level:2,confidence_level:1,trend:"unknown"},{user_id:f.user.id,dimension:"reading",estimate_level:2,confidence_level:2,trend:"improving"}])).error).toBeNull();
    expect((await f.db.from("learner_model_changes").insert({user_id:f.user.id,changed_entity_type:"ability",dimension:"reading",previous_value:{estimate_level:1},new_value:{estimate_level:2,confidence_level:2},reason_category:"test_fixture",change_key:randomUUID()})).error).toBeNull();
    await page.goto("/my-english");for(const label of ["Listening","Speaking","Reading","Writing","Vocabulary","Grammar","Practical communication"])await expect(page.getByRole("heading",{name:label,exact:true})).toBeVisible();await expect(page.getByText("We're still learning about your listening.",{exact:true})).toBeVisible();await expect(page.getByText(/Reading: recent evidence supports/)).toBeVisible();await expect(page.getByRole("heading",{name:"English Score",exact:true})).toHaveCount(0);
    await page.goto("/learn");await page.getByRole("button",{name:"Start learning session",exact:true}).click();await page.getByRole("button",{name:"Skip unscored",exact:true}).click();await page.getByRole("button",{name:"End session",exact:true}).click();await page.goto("/history");await page.getByRole("link",{name:"Open session summary",exact:false}).click();await expect(page.getByRole("heading",{name:"Session summary",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Useful expressions",exact:true})).toBeVisible();
    const foreign=await f.db.auth.admin.createUser({email:`other-${randomUUID()}@example.test`,password:randomUUID(),email_confirm:true});expect(foreign.error).toBeNull();try{const session=await f.db.from("learning_sessions").insert({user_id:foreign.data.user!.id,status:"completed",starting_state_summary:{purpose:"normal_learning_v1"},session_summary:{private:"must-not-leak"}}).select("id").single();expect(session.error).toBeNull();const response=await page.request.get(`/history/${session.data!.id}`);expect(response.status()).toBe(404);expect(await response.text()).not.toContain("must-not-leak");}finally{await f.db.auth.admin.deleteUser(foreign.data.user!.id);}
  }finally{await f.cleanup();}
});
test("product C: settings persist without changing ability or observed effectiveness",async({page})=>{
  await speechMock(page);const f=await fixture(page);try{
    await f.db.from("learner_ability_estimates").insert({user_id:f.user.id,dimension:"listening",estimate_level:3,confidence_level:2});await f.db.from("method_effectiveness").insert({user_id:f.user.id,teaching_method:"conversation",target_skill:"spoken_expression"});
    await page.goto("/settings");await page.getByLabel("Work",{exact:true}).check();await page.getByRole("combobox",{name:"Priority for Work",exact:true}).selectOption("5");await page.getByRole("combobox",{name:"Role-play",exact:true}).selectOption("2");await page.getByRole("combobox",{name:"Correction preference",exact:true}).selectOption("minimal");await page.getByRole("combobox",{name:"Practice pace",exact:true}).selectOption("brisk");await page.getByRole("combobox",{name:"Native / support language",exact:true}).selectOption("zh");await page.getByRole("combobox",{name:"Interface language",exact:true}).selectOption("es");await page.getByRole("button",{name:"Save learning settings",exact:true}).click();await expect(page.getByText(/Preferences saved/)).toBeVisible();
    await page.getByText("Voice preferences",{exact:true}).click();await page.getByRole("combobox",{name:"Response mode",exact:true}).selectOption("typing");await page.getByRole("combobox",{name:"Prompt transcript",exact:true}).selectOption("automatic");await page.reload();await expect(page.getByRole("heading",{name:"Ajustes",exact:true})).toBeVisible();await expect(page.getByRole("combobox",{name:"Role-play",exact:true})).toHaveValue("2");await expect(page.getByRole("combobox",{name:"Priority for Work",exact:true})).toHaveValue("5");await expect(page.getByRole("combobox",{name:"Correction preference",exact:true})).toHaveValue("minimal");await page.getByText("Voice preferences",{exact:true}).click();await expect(page.getByRole("combobox",{name:"Response mode",exact:true})).toHaveValue("typing");await expect(page.getByRole("combobox",{name:"Prompt transcript",exact:true})).toHaveValue("automatic");
    const abilities=await f.db.from("learner_ability_estimates").select("estimate_level,confidence_level").eq("user_id",f.user.id);expect(abilities.data).toEqual([{estimate_level:3,confidence_level:2}]);const effects=await f.db.from("method_effectiveness").select("confidence_level").eq("user_id",f.user.id);expect(effects.data).toEqual([{confidence_level:0}]);
    const saved=await(await page.request.get("/api/settings")).json();const forged=await page.request.post("/api/settings",{headers:{origin:"http://127.0.0.1:3000"},data:{...saved,userId:randomUUID(),abilities:[]}});expect(forged.status()).toBe(400);const csrf=await page.request.post("/api/settings",{headers:{origin:"https://wrong.example"},data:saved});expect(csrf.status()).toBe(403);
    await page.goto("/home");await expect(page.getByText("Arrange a useful meeting time",{exact:true})).toBeVisible();
  }finally{await f.cleanup();}
});
test("product D: membership is a truthful preview using effective entitlement overrides",async({page})=>{
  const f=await fixture(page);try{await page.goto("/membership");await expect(page.getByRole("heading",{name:"Your account: Free",exact:true})).toBeVisible();await expect(page.getByText("Payments are not enabled yet. No payment details are collected.",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:/pay|buy|checkout/i})).toHaveCount(0);const definition=await f.db.from("entitlement_definitions").select("id").eq("entitlement_key","advanced_progress_access").single();expect(definition.error).toBeNull();expect((await f.db.from("user_entitlement_overrides").insert({user_id:f.user.id,entitlement_definition_id:definition.data!.id,value:true,source:"test_fixture"})).error).toBeNull();await page.reload();await expect(page.getByText("Advanced progress: eligible when available · not available yet",{exact:true})).toBeVisible();}finally{await f.cleanup();}
});
test("product E: ads require eligibility and never appear in learning",async({page})=>{
  const f=await fixture(page);const placement=await f.db.from("ad_placement_configs").select("enabled,protected_surface").eq("surface_key","dashboard").single();try{expect(placement.error).toBeNull();await f.db.from("ad_placement_configs").update({enabled:true,protected_surface:false}).eq("surface_key","dashboard");const definition=await f.db.from("entitlement_definitions").select("id").eq("entitlement_key","ads_enabled").single();const override=await f.db.from("user_entitlement_overrides").insert({user_id:f.user.id,entitlement_definition_id:definition.data!.id,value:true,source:"test_fixture"}).select("id").single();expect(override.error).toBeNull();await page.reload();await expect(page.getByRole("complementary",{name:"Ad space"})).toBeVisible();await page.goto("/learn");await expect(page.getByRole("complementary",{name:"Ad space"})).toHaveCount(0);await page.getByRole("button",{name:"Start learning session",exact:true}).click();await expect(page.getByRole("button",{name:"Check response",exact:true})).toBeVisible();await expect(page.getByRole("complementary",{name:"Ad space"})).toHaveCount(0);await f.db.from("user_entitlement_overrides").update({value:false}).eq("id",override.data!.id);await page.goto("/home");await expect(page.getByRole("complementary",{name:"Ad space"})).toHaveCount(0);}finally{if(placement.data)await f.db.from("ad_placement_configs").update(placement.data).eq("surface_key","dashboard");await f.cleanup();}
});
test("product F: incomplete states route to assessment; settings and protected identity remain safe",async({page})=>{
  const f=await fixture(page,false);try{await page.goto("/home");await expect(page).toHaveURL(/\/assessment$/);await f.db.from("profiles").update({onboarding_status:"completed"}).eq("user_id",f.user.id);await page.goto("/learn");await expect(page).toHaveURL(/\/assessment$/);await page.goto("/settings");await expect(page.getByRole("heading",{name:"Account and privacy",exact:true})).toBeVisible();await page.getByRole("button",{name:"Sign out",exact:true}).click();await page.goto("/history");await expect(page).toHaveURL(/\/login/);expect((await page.request.get("/api/settings")).status()).toBe(401);}finally{await f.cleanup();}
});
test("product G: responsive pages and keyboard navigation",async({page})=>{
  const f=await fixture(page);try{for(const width of [390,768,1280]){await page.setViewportSize({width,height:900});for(const path of ["/home","/my-english","/history","/settings","/membership"]){await page.goto(path);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.getByRole("navigation",{name:"Main navigation"})).toBeVisible();}if(width===390)await page.screenshot({path:"test-results/product-membership-mobile.png",fullPage:true});}await page.goto("/home");await page.getByRole("heading",{name:"Current focus",exact:true}).waitFor();await page.getByRole("link",{name:"Adaptive English Everyday words. Real connections.",exact:true}).focus();await page.keyboard.press("Shift+Tab");await expect(page.getByRole("link",{name:"Skip to content",exact:true})).toBeFocused();await page.keyboard.press("Enter");await expect(page.locator("#main-content")).toBeInViewport();}finally{await f.cleanup();}
});
