"use client";
import { useState, useSyncExternalStore } from "react";
import { useRouter } from "next/navigation";
import { methods } from "@/domain/learning/types";
import { correctionLabels, goalKeys, goalLabels, methodLabels, paceLabels, type ProductSettings } from "@/domain/product/settings";
export function SettingsForm({initial}:{initial:ProductSettings}){
  const ready=useSyncExternalStore(()=>()=>{},()=>true,()=>false);
  const [value,setValue]=useState(initial);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [failed,setFailed]=useState(false);const router=useRouter();
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const response=await fetch("/api/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});const data=await response.json();if(!response.ok)throw new Error(data.error);setValue(data);setFailed(false);setMessage("Preferences saved. Future activities will use your choices; measured ability is unchanged.");router.refresh();}catch(e){setFailed(true);setMessage((e as Error).message);}finally{setBusy(false);}}
  return <form onSubmit={save} className="settings-form"><fieldset disabled={busy||!ready}><legend>Learning goals</legend><p>Goals set priorities, not your ability. Choose at least one.</p>{goalKeys.map(key=>{const goal=value.goals.find(g=>g.key===key);return <div className="goal-row" key={key}><label><input type="checkbox" checked={!!goal} onChange={e=>setValue({...value,goals:e.target.checked?[...value.goals,{key,priority:3}]:value.goals.filter(g=>g.key!==key)})}/>{goalLabels[key]}</label><label>Priority for {goalLabels[key]}<select disabled={!goal} value={goal?.priority??3} onChange={e=>setValue({...value,goals:value.goals.map(g=>g.key===key?{...g,priority:Number(e.target.value)}:g)})}>{[[1,"Low"],[2,"Lower"],[3,"Normal"],[4,"High"],[5,"Highest"]].map(([n,label])=><option key={n} value={n}>{label}</option>)}</select></label></div>;})}</fieldset>
    <fieldset disabled={busy||!ready}><legend>Learning preferences</legend><p>These are your choices, not a rating of which methods work best. You can change your mind, including about a previously rejected method.</p><div className="product-grid">{methods.map(key=><label key={key}>{methodLabels[key]}<select value={value.methods[key]} onChange={e=>setValue({...value,methods:{...value.methods,[key]:Number(e.target.value)}})}>{[[-2,"Strongly dislike"],[-1,"Dislike"],[0,"Neutral"],[1,"Prefer"],[2,"Strongly prefer"]].map(([n,label])=><option value={n} key={n}>{label}</option>)}</select></label>)}</div></fieldset>
    <fieldset disabled={busy||!ready}><legend>Correction and pace</legend><div className="product-grid"><label>Correction preference<select value={value.correction} onChange={e=>setValue({...value,correction:e.target.value as ProductSettings["correction"]})}>{Object.entries(correctionLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Practice pace<select value={value.pace} onChange={e=>setValue({...value,pace:e.target.value as ProductSettings["pace"]})}>{Object.entries(paceLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><p>We still adjust difficulty when you need support and help with meaning-critical mistakes.</p></fieldset>
    <fieldset disabled={busy||!ready}><legend>Language</legend><div className="product-grid">{(["interfaceLanguage","nativeLanguage"] as const).map(key=><label key={key}>{key==="interfaceLanguage"?"Interface language":"Native / support language"}<select value={value[key]} onChange={e=>setValue({...value,[key]:e.target.value})}><option value="en">English</option><option value="zh">中文</option><option value="es">Español</option></select></label>)}</div><p>Chinese, English and Spanish are supported for navigation and assessment support. Some learning and settings text remains in English.</p></fieldset>
    <div className="save-bar"><button className="primary" disabled={busy||!ready}>{busy?"Saving…":"Save learning settings"}</button><p role={failed?"alert":"status"}>{message}</p></div></form>;
}
