import { describe, it, expect, vi } from "vitest";
import Stripe from "stripe";
import { allowedPrice, allowance, displayAmount, billingConfig, subscriptionStatus } from "./policy";
import { StripeTestProvider } from "../../../scripts/billing-provider";
import { subscriptionActive, adEligible } from "../product/commercial";
import { adSenseConfiguration, adDeliveryEnabled } from "../ads/provider";
import { deploymentReady, siteOrigin } from "../../lib/deployment";
const env={STRIPE_SECRET_KEY:"sk_test_fixture",STRIPE_WEBHOOK_SECRET:"whsec_fixture",STRIPE_PREMIUM_MONTHLY_PRICE_ID:"price_month",STRIPE_PREMIUM_YEARLY_PRICE_ID:"price_year"};
function fixture(){
  const sdk={prices:{retrieve:vi.fn().mockResolvedValue({id:"price_month",livemode:false,active:true,type:"recurring",recurring:{interval:"month",interval_count:1,usage_type:"licensed"},unit_amount:123,currency:"usd",billing_scheme:"per_unit"})},customers:{create:vi.fn().mockResolvedValue({id:"cus_fixture",livemode:false}),retrieve:vi.fn().mockResolvedValue({id:"cus_fixture",livemode:false}),del:vi.fn().mockResolvedValue({deleted:true})},subscriptions:{list:vi.fn().mockResolvedValue({data:[],has_more:false})},checkout:{sessions:{list:vi.fn().mockResolvedValue({data:[],has_more:false}),expire:vi.fn(),create:vi.fn().mockResolvedValue({url:"https://checkout.stripe.com/test",livemode:false})}},billingPortal:{sessions:{create:vi.fn().mockResolvedValue({url:"https://billing.stripe.com/test"})}}};
  return {sdk,provider:new StripeTestProvider(env,sdk as unknown as Stripe)};
}
describe("test billing policy and adapter",()=>{
  it("fails closed without credentials/prices",()=>{expect(billingConfig({}).ready).toBe(false);expect(()=>allowedPrice({},"month")).toThrow();});
  it("rejects live keys before any network call",()=>{expect(()=>new StripeTestProvider({...env,STRIPE_SECRET_KEY:"sk_live_fixture"})).toThrow("test keys");});
  it("only resolves configured intervals and rejects ambiguous pricing",()=>{expect(allowedPrice(env,"month")).toBe("price_month");expect(()=>allowedPrice({...env,STRIPE_PREMIUM_YEARLY_PRICE_ID:""},"year")).toThrow();expect(()=>billingConfig({...env,STRIPE_PREMIUM_YEARLY_PRICE_ID:"price_month"})).toThrow();});
  it("retrieves configured test prices rather than inventing amounts",async()=>{const {sdk,provider}=fixture();await provider.checkout("cus_owner","month","https://app.example");expect(sdk.prices.retrieve).toHaveBeenCalledWith("price_month");expect(sdk.checkout.sessions.create).toHaveBeenCalledWith(expect.objectContaining({customer:"cus_owner",mode:"subscription",line_items:[{price:"price_month",quantity:1}]}));});
  it("rejects live, inactive and wrong-interval prices",async()=>{for(const patch of [{livemode:true},{active:false},{recurring:{interval:"year"}},{unit_amount:null}]){const {sdk,provider}=fixture();sdk.prices.retrieve.mockResolvedValue({...await sdk.prices.retrieve(),...patch});await expect(provider.checkout("cus_owner","month","https://app.example")).rejects.toThrow();expect(sdk.checkout.sessions.create).not.toHaveBeenCalled();}});
  it("prevents duplicate active subscriptions",async()=>{const {sdk,provider}=fixture();sdk.subscriptions.list.mockResolvedValue({data:[{status:"active"}],has_more:false});await expect(provider.checkout("cus_owner","month","https://app.example")).rejects.toThrow("existing");});
  it("expires abandoned sessions before a replacement checkout",async()=>{const {sdk,provider}=fixture();sdk.checkout.sessions.list.mockResolvedValue({data:[{id:"cs_old",livemode:false}],has_more:false});await provider.checkout("cus_owner","month","https://app.example");expect(sdk.checkout.sessions.expire).toHaveBeenCalledWith("cs_old");});
  it("keeps customer creation free of learner data and idempotent",async()=>{const {sdk,provider}=fixture();await provider.customer("user");expect(sdk.customers.create).toHaveBeenCalledWith({},{idempotencyKey:"customer:user"});});
  it("creates a portal only for the passed server-owned test customer",async()=>{const {sdk,provider}=fixture();await provider.portal("cus_owner","https://app.example");expect(sdk.billingPortal.sessions.create).toHaveBeenCalledWith({customer:"cus_owner",return_url:"https://app.example/membership"});sdk.customers.retrieve.mockResolvedValue({id:"cus_owner",livemode:true});await expect(provider.portal("cus_owner","https://app.example")).rejects.toThrow();});
  it("verifies real SDK signatures and rejects tampering, old timestamps and live events",()=>{const sdk=new Stripe(env.STRIPE_SECRET_KEY),provider=new StripeTestProvider(env);const payload=JSON.stringify({id:"evt_signed",type:"customer.subscription.updated",livemode:false,data:{object:{customer:"cus_owner"}}});const signature=sdk.webhooks.generateTestHeaderString({payload,secret:env.STRIPE_WEBHOOK_SECRET});expect(provider.verify(payload,signature)).toEqual({id:"evt_signed",customer:"cus_owner"});expect(()=>provider.verify(payload+" ",signature)).toThrow();const old=sdk.webhooks.generateTestHeaderString({payload,secret:env.STRIPE_WEBHOOK_SECRET,timestamp:1});expect(()=>provider.verify(payload,old)).toThrow();const live=payload.replace('"livemode":false','"livemode":true');expect(()=>provider.verify(live,sdk.webhooks.generateTestHeaderString({payload:live,secret:env.STRIPE_WEBHOOK_SECRET}))).toThrow("Live");});
  it("maps payment failure and expiry conservatively",()=>{expect(["active","trialing","canceled","incomplete_expired","past_due","unpaid","paused"].map(subscriptionStatus)).toEqual(["active","trial","canceled","expired","payment_issue","payment_issue","payment_issue"]);});
  it("uses current provider state and preserves cancel-at-period-end access",async()=>{const {sdk,provider}=fixture();sdk.subscriptions.list.mockResolvedValue({data:[{id:"sub_test",created:1,start_date:100,status:"active",livemode:false,cancel_at_period_end:true,items:{data:[{price:{id:"price_month"},quantity:1,current_period_end:200}]}}],has_more:false});const state=await provider.snapshot("cus_owner");expect(state?.cancel).toBe(true);expect(subscriptionActive({status:state!.status,started_at:state!.start,ends_at:state!.end},new Date(150000))).toBe(true);expect(subscriptionActive({status:state!.status,started_at:state!.start,ends_at:state!.end},new Date(200000))).toBe(false);});
  it("deletion cancels test customer billing and refuses live deletion",async()=>{const {sdk,provider}=fixture();await provider.remove("cus_owner");expect(sdk.customers.del).toHaveBeenCalledWith("cus_owner");sdk.customers.del.mockClear();sdk.customers.retrieve.mockResolvedValue({id:"cus_owner",livemode:true});await expect(provider.remove("cus_owner")).rejects.toThrow("Live");expect(sdk.customers.del).not.toHaveBeenCalled();});
  it("null allowance means unlimited and configured zero means no provider calls",()=>{expect(allowance(null)).toBeNull();expect(allowance(0)).toBe(0);expect(allowance(50)).toBe(50);expect(()=>allowance(-1)).toThrow();});
});
describe("deployment and advertising",()=>{
  it("formats Stripe minor units including special currency cases",()=>{expect(displayAmount(123,"usd","en")).toBe("$1.23");expect(displayAmount(100,"jpy","en")).toContain("100");expect(displayAmount(100,"isk","en")).toContain("1");expect(displayAmount(100,"isk","en")).not.toContain("100");});
  it("never defaults production redirects to localhost",()=>{expect(()=>siteOrigin({NODE_ENV:"production"})).toThrow();expect(siteOrigin({NODE_ENV:"development"})).toContain("127.0.0.1");expect(()=>siteOrigin({VERCEL:"1",NEXT_PUBLIC_SITE_URL:"http://localhost:3000"})).toThrow();});
  it("rejects local database and missing cron configuration on hosted deployments",()=>{expect(deploymentReady({VERCEL:"1",NEXT_PUBLIC_SITE_URL:"https://app.example",NEXT_PUBLIC_SUPABASE_URL:"http://127.0.0.1:54321",NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:"fixture",SUPABASE_SERVICE_ROLE_KEY:"fixture"})).toBe(false);});
  it("has no external ads without real config or without explicit test enablement",()=>{expect(adDeliveryEnabled({NODE_ENV:"production"})).toBe(false);expect(adDeliveryEnabled({NODE_ENV:"development",ADSENSE_DELIVERY_ENABLED:"true"})).toBe(false);expect(adDeliveryEnabled({NODE_ENV:"production",ADSENSE_DELIVERY_ENABLED:"false"})).toBe(false);expect(adSenseConfiguration({},"dashboard")).toBeNull();expect(adSenseConfiguration({ADSENSE_TEST_ENABLED:"true"},"dashboard")).toBeNull();expect(adSenseConfiguration({ADSENSE_TEST_ENABLED:"live"},"dashboard")).toBeNull();});
  it("denies protected, disabled, and premium placements",()=>{expect(adEligible({ads_enabled:true},{enabled:true,protected_surface:false},"assessment",false)).toBe(false);expect(adEligible({ads_enabled:true},{enabled:false,protected_surface:false},"dashboard",false)).toBe(false);expect(adEligible({ads_enabled:false},{enabled:true,protected_surface:false},"dashboard",false)).toBe(false);});
});
